# Generated by Django 4.1 on 2022-09-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coache', '0001_initial'),
        ('sportsman', '0001_initial'),
        ('sport_school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsmanInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('insuranse', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coache', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='coache.coachemodel')),
                ('sport_school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sport_school.sportschoolmodel')),
                ('sportsman', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sportsman.sportsmanmodel')),
            ],
            options={
                'db_table': 'fl_sportsman_info',
                'unique_together': {('period', 'sport_school', 'sportsman', 'coache')},
            },
        ),
    ]
