# Generated by Django 4.1 on 2022-11-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsmaninfomodel',
            options={'verbose_name': 'Запись по спортсмену', 'verbose_name_plural': 'Информация о спортсменах'},
        ),
    ]
