# Generated by Django 4.1 on 2022-09-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_value', '0001_initial'),
        ('tournament', '0002_alter_tournamentmodel_type_of_tornament'),
        ('sportsman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_value', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='category_value.categoryvaluemodel')),
                ('sportsman', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sportsman.sportsmanmodel')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tournament.tournamentmodel')),
            ],
            options={
                'db_table': 'fl_tournament_info',
                'unique_together': {('period', 'tournament', 'sportsman', 'category_value')},
            },
        ),
    ]
