# Generated by Django 4.1 on 2022-11-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentinfomodel',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Информация о турнирах'},
        ),
        migrations.AddField(
            model_name='tournamentinfomodel',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
