# Generated by Django 4.1 on 2022-09-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sport_school', '0001_initial'),
        ('type_of_tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreScaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('place_from', models.IntegerField()),
                ('place_to', models.IntegerField()),
                ('numbers_of_points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport_school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sport_school.sportschoolmodel')),
                ('type_tournament', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='type_of_tournament.typeoftournamentmodel')),
            ],
            options={
                'db_table': 'fl_score_scale',
                'unique_together': {('period', 'sport_school', 'type_tournament')},
            },
        ),
    ]
