# Generated by Django 4.1 on 2022-11-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_scale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorescalemodel',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Шкала'},
        ),
    ]
