# Generated by Django 4.1 on 2022-09-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportschoolmodel',
            options={'verbose_name': 'Спортивную школу', 'verbose_name_plural': 'Спортивные школы'},
        ),
    ]
