# Generated by Django 4.1 on 2022-09-03 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type_of_tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('date_tournament', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_of_tornament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type_of_tournament.typeoftournamentmodel')),
            ],
            options={
                'db_table': 'fl_tournament',
            },
        ),
    ]
