# Generated by Django 4.1 on 2022-09-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type_of_tournament', '0001_initial'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='type_of_tornament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='type_of_tournament.typeoftournamentmodel'),
        ),
    ]
