# Generated by Django 4.1 on 2022-09-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsmanmodel',
            options={'verbose_name': 'Спортсмена', 'verbose_name_plural': 'Спортсмены'},
        ),
    ]
