# Generated by Django 4.1 on 2022-09-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_value', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryvaluemodel',
            options={'verbose_name': 'Тип категории', 'verbose_name_plural': 'Типы категорий'},
        ),
    ]
